# Generated by Django 4.0.1 on 2022-01-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('part_of_word', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('pronoun', 'Pronoun'), ('adverb', 'Аdverb'), ('numeral', 'Numeral')], max_length=100, verbose_name='Part_speech')),
            ],
        ),
    ]
